model: BERT4Rec
dataset: instacart
data_path: ./recbole_data


USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
TIME_FIELD:  timestamp
load_col:
  inter: [user_id, item_id, timestamp]
MAX_ITEM_LIST_LENGTH: 100


hidden_size:      128 
n_layers:         2
n_heads:          4
mask_ratio:       0.2 
loss_type:        CE
train_neg_sample_args: ~
hidden_dropout_prob: 0.5
attn_dropout_prob:   0.5


epochs:           10
train_batch_size: 1024
learning_rate:    0.001
eval_step:        1
stopping_step:    10
metrics: [Recall, NDCG, Hit, MRR]
topk: [5, 10, 20]
seed: 2025

device: cuda